### ISSUE TITLE
[FEAT] login 기능 구현

### ISSUE THREAD

**Issue by soonvro** [onesix123/untitled#17]
# Description
roccia 901 Api를 이용한 로그인과 토큰 저장 기능을 구현합니다.

# Todo
- [ ] 토큰을 저장할 앱 내부 저장소 구현
- [ ] Api URL 등의 정보를 제공하는 interface 설계 및 구현
- [ ] 사용자 인증을 관리하는 Repository 구현
- [ ] 화면을 Repository에 연결할 ViewModel 구현
