### ISSUE TITLE
[FEAT] 출석 기능 API 연결 및 상호작용 추가

### ISSUE THREAD

**Issue by soonvro** [onesix123/untitled#19]
# Description
출석기능을 위한 API 통신을 구현하고 화면의 상호작용과 연결합니다.

# Todo
- [ ] 출석 Repository 구현
- [ ] 출석 기능과 관련된 domain model 정의
- [ ] 화면 상호작용으로 출석 기능 제어
- [ ] 화면에 출석 Viewmodel 데이터 바인딩
